### ISSUE TITLE
Create tool for automatic download and resizing of album covers

### ISSUE THREAD

**Issue by mluogh** [dingers-music/dingers-music.github.io#7]
It is annoying to download the album cover and resize it. 

I propose we add a tool to automate this process.

**Comment by mingyli** [comment]
current workflow:
1. download image
2. resize it
3. move to assets

what would your suggested workflow look like?
1. download image
2. use tool to resize it
3. move to assets

**Comment by mluogh** [comment]
My suggested workflow:

1. run script with link address of image 
   - tool does resizing and moving to assets

**Comment by mingyli** [comment]
All you need to do is
```
convert ~/Downloads/image.jpg -resize 500x500 ~/dingers.github.io/assets/images/image.jpg
```

**Comment by mluogh** [comment]
This still requires me to wget!
